### ISSUE TITLE
Error loading example JSON

### ISSUE THREAD

**Issue by pgleeson** [deepforge-dev/webgme-json-importer#1]
Hi @brollb, I've managed to get this locally installed and followed the instructions here: https://github.com/deepforge-dev/webgme-json-importer/tree/master/examples, though neither of the JSON example files seemed to load correctly:

<img width="1338" alt="Screenshot 2021-04-01 at 18 18 57" src="https://user-images.githubusercontent.com/1556687/113330716-f5f57580-9316-11eb-8f32-e3c03f1de454.png">

As opposed to "Select the JSON to use in the configuration menu and click "Run"!" (I couldn't find the configuration menu for the FCO_mdf..?), I just pressed Run and set the JSON there (tried one file after the other)... 

Sorry, complete webgme newbie here...

**Comment by brollb** [comment]
No worries! I should have probably made better instructions :)

I think the problem is that you are running it on the "ROOT" node rather than an instance of the FCO. It should work if you (after creating a new project):
- drag the FCO node from the lower left onto the center panel
- open the newly created instance of FCO
- run the plugin (like it looks like you did!)

**Comment by pgleeson** [comment]
Great! I've managed to create something...

<img width="870" alt="Screenshot 2021-04-01 at 19 20 49" src="https://user-images.githubusercontent.com/1556687/113337252-70c28e80-931f-11eb-9961-fe2b69eaaf81.png">

cc @jdcpni

**Comment by brollb** [comment]
Nice! Does the flow make more sense now? I probably should have been more explicit that the plugin is really taking some arbitrary node and then modifying it to reflect the state of the JSON. This is why a new instance of FCO needed to be created and we couldn't simply run the plugin on the "ROOT" node.

Now, we should just need to write some transformation code to convert the mdf schematic into this format and we should be all set! Do you feel comfortable giving that a go or would you rather I take a pass at it?

Also, if you create an instance of "Node" and then synchronize it with the [nodes_edges.json](https://github.com/deepforge-dev/webgme-json-importer/blob/master/examples/nodes_edges.json) example, it should create a model instance.
