### ISSUE TITLE
GMEJSONNode and Typescript Refactor

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/webgme-json-importer#30]
Based on a conversation with @brollb, we decided that it might be nice to add additional support with typescript for `webgme-json-importer` json format that adheres to the schema.

**Comment by brollb** [comment]
It is worth noting that using types should prevent internal bugs (or bugs when calling from typescript) but won't do any runtime checking. For that, we would need something like JSON schema (or using rust and wasm but that is a bigger jump and probably wouldn't be worth the bigger effort).

**Comment by brollb** [comment]
We could also use something like [TypeDoc](https://typedoc.org/) potentially
