### ISSUE TITLE
Allow picking keys during export

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/webgme-json-importer#34]
The `WJI` format can get quite verbose and the `toJSON` sometimes contains properties which are not necessarily relavent to the client application. Hence, can the signature `toJSON(node, shallow)`  be modified to `toJSON(node, attributes=['children', 'pointers', ....])`? I am fine with the previous signature or a signature like `toJSON(node, omitAttributes=['children', 'pointers', ...])`

**Comment by brollb** [comment]
This sounds good but it might be nice to use a `Set` rather than an index as I would expect it to have better performance than using an array (and the position doesn't have any meaning here).
