### ISSUE TITLE
Allow diffing/patching of from states. 

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/webgme-json-importer#36]
It might be nice to allow diffing/patching using state jsons, which will then be used to compute patches based on certain selectors (as done with GME nodes) and apply updates to the subtree based on diffs. This was originally proposed by @brollb in [scm](https://github.com/symbench/scm)'s annotator widget, which then was side-tracked by another idea to compare annotations as flat data structures. However, upon further thought, this makes a lot of sense.

Something like:

```js
Importer.prototype.getDiff = (state1, state2) => {
// ToDo: Implement certain 
}

Importer.prototype.applyDiff = (patches) => {
// ToDo: Handle creation/deletion/updates based on these patches.
}
```

**Comment by brollb** [comment]
Ideally, this will update the internal implementation to use these methods as well. We will also need to make sure to have an optional `resolvedSelectors` argument for each of the methods so we don't have to re-resolve the ID fields to actual nodes.
